### ISSUE TITLE
Feedback - Tenant provider

### ISSUE THREAD

**Issue by rneuter** [funkymed/tenant-aware-bundle#1]
Hello there,

Firstable, as a Symfony lover & SaaS maker, very good job and thank you for this package!

Also, I would like to suggest a feature that could increase the adoption of this package. My point is that pretty sure that in this kind of industry, there are different ways to load a tenant configuration.

One example could be getting the DB credentials from a secret manager (something like `GET https://my-secret-manager.app/tenant/{tenant-uuid}/v2`). Also, let's say that an user is authenticated with a JWT token with the tenant-id in the claim, I don't need to load the Tenant entity from the shared DB. Purely hypothetical, but you'll get the idea.

So if I'm not wrong while interpreting this package code, I'll not be able to use this package as 
‎`TenantConfigurationPass‎` explicitly loads the Tenant entity from the entity manager. My suggestion:

- `Entity\Tenant` => `Dto\Tenant` without explicit dependency to Doctrine ORM
  - `public function getIdentifier(): string`
- `Provider` namespace
  - `ProviderInterface` (`public function provide(): Tenant`)
  - `HostNameProvider` => takes the responsibility to get the tenant hostname from the kernel parameter, so it's not the job of `TenantConfigurationPass::process` any more
  - So hypothetically I can make a `JWTProvider` which will decode & verify the token, plus returning a Tenant with its ID
  - There is probably a need to tag service implementing `ProviderInterface` so it (they?) can be got from the container

- `TenantConfigurationPass‎`
  - Load the `Dto\Tenant` from a provider
  - Calls whatever `new Processor($tenant, $container);`
  - `DatabaseProcessor` can now take the responsibility to fetch the tenant config from the DB, and updates the DBAL configuration
  - I can now implement my own `DatabaseFromSecretManagerProcessor` which will fetch credentials from my secret manager

Also, could be great that processors have access to a [PSR-6 cache](https://www.php-fig.org/psr/psr-6/), so my processor does not need to hit my secret manager on every HTTP request.

What do you think? I had to finish this comment quickly, sorry if I misunderstood something or if I'm not clear enough. I'll be glad to hear your opinion :)

Thank you, and once again, good job!

**Comment by petski** [comment]
Thank you @funkymed for your [blog post](https://medium.com/@cyrilgeorgespereira/multi-tenant-and-symfony-b4b69c187f36) and this repo (!).

@rneuter's approach also allows tenant identification to be done based on the URL-path, for example yourdomain.io/tenant1/... (`bin/console` should then accept a `--tenant` instead of a `--hostname`)

**Comment by funkymed** [comment]
Hi @rneuter 
Thanks for your feedback.

> One example could be getting the DB credentials from a secret manager (something like GET https://my-secret-manager.app/tenant/{tenant-uuid}/v2). 

Using GET https://my-secret-manager.app/tenant/{tenant-uuid}/v2 is too much permissive, and i don't think it's a good idea to expose any credential from an api like this even you need to authenticate yourself.

> Also, could be great that processors have access to a [PSR-6 cache](https://www.php-fig.org/psr/psr-6/), so my processor does not need to hit my secret manager on every HTTP request.

If you take a good look of the code, everything we do to get the credentials are done during the creation of the cache, so the next time you will use it.

> So if I'm not wrong while interpreting this package code, I'll not be able to use this package as
‎TenantConfigurationPass‎ explicitly loads the Tenant entity from the entity manager. My suggestion:

I am not sure to understand your point about the provider. 
The switch of credential is automatic and setted by HostName.
No need to use a TenantProvider to get the data of the HostName tenant database.

Regards

Cyril
